export default {
    background: require('../assets/BG.jpg'),
    telegram: require('../assets/telegram.png'),
    image_login: require('../assets/image_login.png'),
    icon_facebook:require('../assets/facebook_icon.png'),
    icon_google: require('../assets/google_icon_1.png'),
    image_register:require('../assets/image_register.png'),
    image_updateprofile:require('../assets/Settings/user-profile.png'),
    image_changePass:require('../assets/Settings/padlock.png'),
    image_About:require('../assets/Settings/info.png'),
    image_signOut: require('../assets/Settings/out.png'),
    tabbar_home:  require('../assets/tabbar/home-2.png'),
    tabbar_chat: require('../assets/tabbar/chat.png'),    
    tabbar_notification: require('../assets/tabbar/notification.png'),
    tabbar_profile: require('../assets/tabbar/user-2.png'),
    tabbar_myteams:require('../assets/tabbar/group.png'),
    tabbar_appointment: require('../assets/tabbar/schedule.png'),
    scanner: require('../assets/Settings/scan.png'),
    joinclass: require('../assets/Settings/add.png'),
    back: require('../assets/Settings/left-arrow.png'),
    tabbar_home_1:  require('../assets/tabbar/home.png'),
    tabbar_myteams_1:require('../assets/tabbar/group (1).png'),
    tabbar_appointment_1: require('../assets/tabbar/calendar.png'),
    tabbar_notification_1: require('../assets/tabbar/notification-1.png'),
    tabbar_profile_1: require('../assets/tabbar/user.png'),
    delete:require('../assets/Settings/delete.png'),
}